cmake_minimum_required (VERSION 3.10)
project(Rasterizer)
set(OpenCV_DIR "D:/GAMES101_Code/opencv_install")
find_package(OpenCV REQUIRED)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(EIGEN_ROOT "D:/GAMES101_Code/eigen-5.0.0")
include_directories(${EIGEN_ROOT})
message(STATUS "Eigen include path: ${EIGEN_ROOT}")
add_executable(Rasterizer main.cpp rasterizer.hpp rasterizer.cpp global.hpp Triangle.hpp Triangle.cpp Texture.hpp Texture.cpp Shader.hpp OBJ_Loader.h)
target_include_directories(Rasterizer PRIVATE ${EIGEN_ROOT})
target_link_libraries(Rasterizer ${OpenCV_LIBRARIES})
#target_compile_options(Rasterizer PUBLIC -Wall -Wextra -pedantic)